name: "#outrunthewolf"
description: "I hate you"
title: "outrunthewolf"
version: 1.1.2

url: "http://outrunthewolf.com"
baseurl: /
analytics: "UA-34540071-1"

paginate: 10
permalink: pretty

# Twitter Shit
twitterCard: "summary"
twitterCreator: "@outrunthewolf"
twitterLink: "http://twitter.com/outrunthewolf"

# Facebook stuff

# Google Stuff
googleLink: "http://plus.google.com/outrunthewolf"
googleCreator: Google+

# Github
githubLink: "https://github.com/outrunthewolf"
